// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGpEJPtqxkKRiSMKr_9xrMri-8lHXMGJI',
    appId: '1:831661784404:web:5dd1d12cf7c39a0e461cc1',
    messagingSenderId: '831661784404',
    projectId: 'transfer-money-app',
    authDomain: 'transfer-money-app.firebaseapp.com',
    databaseURL: 'https://transfer-money-app-default-rtdb.firebaseio.com',
    storageBucket: 'transfer-money-app.appspot.com',
    measurementId: 'G-BPKJVJLKYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcDo18JN0mLhPmP5DaI5AEhRfpkyw3Dp4',
    appId: '1:831661784404:android:0a01e7db07986b1a461cc1',
    messagingSenderId: '831661784404',
    projectId: 'transfer-money-app',
    databaseURL: 'https://transfer-money-app-default-rtdb.firebaseio.com',
    storageBucket: 'transfer-money-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrmHRLitguTKoDnjnZvRNsi6bvI-ucll8',
    appId: '1:831661784404:ios:c748bd315adbce14461cc1',
    messagingSenderId: '831661784404',
    projectId: 'transfer-money-app',
    databaseURL: 'https://transfer-money-app-default-rtdb.firebaseio.com',
    storageBucket: 'transfer-money-app.appspot.com',
    iosBundleId: 'com.example.novo',
  );
}
